### ISSUE TITLE
Cannot use host with port specifier

### ISSUE THREAD

**Issue by rhpijnacker** [FlexMeasures/flexmeasures-client#86] opened 2024-09-30 10:11 UTC
When I try to use FlexMeasuresClient with a `<host>:<port>` combination:

```
    client = FlexMeasuresClient(
        host = '192.168.123.123:5000',
        email = email,
        password = password,
        ssl = False,
    )
```

then I get an error trying to get an access token:
```
    token = await client.get_access_token()
```

This results in:
```
Traceback (most recent call last):
  File "./client.py", line 23, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "./client.py", line 21, in main
    token = await client.get_access_token()
  File "/.../lib/python3.9/site-packages/flexmeasures_client/client.py", line 234, in get_access_token
    response, _status = await self.request(
  File "/.../lib/python3.9/site-packages/flexmeasures_client/client.py", line 114, in request
    url = self.build_url(uri, path=path)
  File "/.../lib/python3.9/site-packages/flexmeasures_client/client.py", line 227, in build_url
    url = URL.build(scheme=self.scheme, host=self.host, path=path).join(
  File "/.../lib/python3.9/site-packages/yarl/_url.py", line 385, in build
    netloc = cls._make_netloc(
  File "/.../lib/python3.9/site-packages/yarl/_url.py", line 1057, in _make_netloc
    ret = cls._encode_host(host)
  File "/.../lib/python3.9/site-packages/yarl/_url.py", line 1038, in _encode_host
    _host_validate(host)
  File "/.../lib/python3.9/site-packages/yarl/_url.py", line 1607, in _host_validate
    raise ValueError(
ValueError: Host '192.168.123.123:5000' cannot contain ':' (at position 12)
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7fe0a04751f0>
```

**Comment by nhoening** [comment] 2024-09-30 10:22
Looks like a regression (maybe through newer yarl version?) , as we used `host: str = "localhost:5000"` as default setting ourselves.

We should:
- add `self.port` as a variable
- in the  `__post_init__`, extract the potential port from the `host` parameter with regex

Happy to see a PR.
Our attention is currently not on this client, but will be in the near future again - we'll need it in some projects.

**Comment by rhpijnacker** [comment] 2024-09-30 15:52
I understand this is not a priority for you, but it breaks my V2G Liberty setup. So I would appreciate if you could take a look at the PR.

**Comment by nhoening** [comment] 2024-09-30 20:43
First of all, I cannot reproduce this locally:

```
(fm-3.10) nicolas at pop-os in ~/workspace/seita/flexmeasures-client/src on main (1 changed, 1 untracked)
± python          
Python 3.10.12 (main, Jul 29 2024, 16:56:48) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from flexmeasures_client import FlexMeasuresClient
>>> client = FlexMeasuresClient(email="bla@bla.de", password="blupp", host="127.0.0.1:5000", ssl=False)
>>> client
FlexMeasuresClient(password='blupp', email='bla@bla.de', host='127.0.0.1:5000', ssl=False, api_version='v3_0', path='/api/v3_0/', access_token=None, max_polling_steps=10, polling_timeout=200.0, request_timeout=20.0, polling_interval=10.0, session=None)
>>> 
(fm-3.10) nicolas at pop-os in ~/workspace/seita/flexmeasures-client/src on main (1 changed, 1 untracked)
± pip list | grep yarl
WARNING: Ignoring invalid distribution -ypy (/home/nicolas/envs/fm-3.10/lib/python3.10/site-packages)
yarl                          1.13.1
```

Can you see which version of yarl you are using? 

How did you install it? I am checking the config of this repo, but it doesn't seem to be explicitly mentioned, like in `install_requires`. I had to install it myself...

**Comment by rhpijnacker** [comment] 2024-10-01 05:53
I used `pip install flexmeasures-client`.
However, I could also reproduce it by using the source code.
I extracted the body of `build_url`, which also reproduces it.

**Closed** 2024-10-02 14:25 UTC
